### ISSUE TITLE
Floating point logic

### ISSUE THREAD

**Issue by zitounh** [cristina-serban/smtlib-parser#1]
Hi, 

I'm trying to use your parser to convert smt files into another format.

I added new theory QF_FP.smt2 in your tool to handle smt files which use floating point logic. When I run your parser on those smt files (any file from QF_FP section of http://smtlib.cs.uiowa.edu/benchmarks.shtml), its didn't work.  Dedicated floating point sorts, funs, ... are unknown (Unknown sort '( _ FloatingPoint 11 53)' (9:19 - 9:41)). 

Its seems that I need to review FloatingPoint.smt2 file to deal with this issue.  Do I misuse your tool, or it's a correct way to do it ? Do you have working FloatingPoint.smt2 file ? 

Best,
Heytem

**Comment by cristina-serban** [comment]
Hello,

The issues you are experiencing are due to some shortcomings of the sortedness checker. In particular, it does not handle indexed sorts that well, which is why you are getting that error. Good news is that you don't need it for what you want to do.

Replace `exec.checkSortedness();` on line 34 in `main.cpp` with either a call to `checkSyntax()` or simply `parse()`.  Both of these work as intended, the input file will get parsed correctly, and the abstract syntax tree is stored in the `ast` field of the `SmtExecution` class. 

All you need now is to implement a translator from my `ast` hierarchy to whatever you want. I even have an example for you: https://github.com/cristina-serban/inductor/blob/master/smtlib/sep/transl. This translates my `ast` hierarchy into a more specialized one for Separation Logic. You can write one for whatever you want and then use it on the `ast` field of the `exec` object from `main.cpp`.

Let me know if you require further assistance. I was late to reply due to being away on holiday.

Best,
Cristina

**Comment by zitounh** [comment]
Thanks for your response. 

I will try as you suggest.

Best,
Heytem
